version: '2.3'
services:
  centernet-1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: root #${USER_ID:-1000}
    runtime: nvidia  # TODO: Exchange with "gpu: all" in the future (see https://github.com/facebookresearch/detectron2/pull/197/commits/00545e1f376918db4a8ce264d427a07c1e896c5a).
    shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ./data/coco:/home/root/CenterNet-1/data/coco
      - ./exp:/home/root/CenterNet-1/exp
      - ./src/runs:/home/root/CenterNet-1/src/runs
      - ./models:/home/root/CenterNet-1/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    pid: "host"

